/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import audio.AePlayWave;
import audio.PlayAudio;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Haro
 */
public class JuegoGato extends javax.swing.JFrame {

    /**
     * Creates new form JuegoGato
     */
    
    public JuegoGato() {
        initComponents();
      
        
       
        
    
        TxtUser1.setText("Tu turno"); 
    TxtUser2.setText("Espera"); 
     String player1;
     String player2;
     player1=JOptionPane.showInputDialog("Nombre del jugador 1");
     player2=JOptionPane.showInputDialog("Nombre del jugador 2");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtUser1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtUser2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        limp = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(255, 255, 153));
        jLabel1.setFont(new java.awt.Font("BatangChe", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/benito bodoque.jpg"))); // NOI18N
        jLabel1.setText("Juego del Gato");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(2, 2));
        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel3.setLayout(new java.awt.GridLayout(2, 2));

        jLabel3.setText("Jugador 1");
        jPanel3.add(jLabel3);

        TxtUser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUser1ActionPerformed(evt);
            }
        });
        jPanel3.add(TxtUser1);

        jLabel2.setText("Jugador 2");
        jPanel3.add(jLabel2);

        TxtUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUser2ActionPerformed(evt);
            }
        });
        jPanel3.add(TxtUser2);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        limp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/res.jpg"))); // NOI18N
        limp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpMouseClicked(evt);
            }
        });
        limp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpActionPerformed(evt);
            }
        });
        jPanel4.add(limp);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.jpg"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton1.setText("jButton1");
        jPanel5.add(jButton1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3));

        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel2.add(boton1);

        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton2MouseClicked(evt);
            }
        });
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        jPanel2.add(boton2);

        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton3MouseClicked(evt);
            }
        });
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        jPanel2.add(boton3);

        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton4MouseClicked(evt);
            }
        });
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        jPanel2.add(boton4);

        boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton5MouseClicked(evt);
            }
        });
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        jPanel2.add(boton5);

        boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton6MouseClicked(evt);
            }
        });
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        jPanel2.add(boton6);

        boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton7MouseClicked(evt);
            }
        });
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        jPanel2.add(boton7);

        boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton8MouseClicked(evt);
            }
        });
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        jPanel2.add(boton8);

        boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg"))); // NOI18N
        boton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton9MouseClicked(evt);
            }
        });
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        jPanel2.add(boton9);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero2
    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        
// TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton2ActionPerformed

    private void TxtUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUser2ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 3
    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton3ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 4
    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton4ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 5
    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
       try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
    }//GEN-LAST:event_boton5ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 6
    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        // TODO add your handling code here
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton6ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 7
    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton7ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 8
    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton8ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 9
    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        // TODO add your handling code here:
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton9ActionPerformed
//En esta parte del código nos permiye agregar lo que es el sondo del boton numero 1
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        try {
            AePlayWave aw;
            URL url = PlayAudio.class.getResource("/audio/miau.wav");
            aw = new AePlayWave(url);
            aw.start();
        } catch (URISyntaxException ex) {
            Logger.getLogger(PlayAudio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
   if (TxtUser1.getText().equals("Tu turno")){//nos permite verificar que en realidad la caja contenga ese valor
       boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));//agregamos lo que es la imagen al boton
       
       TxtUser1.setText("Espera");//la caja de texto 1 tiene el valor espera
       TxtUser2.setText("Tu turno");//la caja de texto 2 tiene el valor tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja

   }  else if (TxtUser2.getText().equals("Tu turno")){//nos permite verificar que en realidad la caja contenga ese valor
       boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));//agregamos lo que es la imagen al boton
     
       TxtUser1.setText("Tu turno");//la caja de texto 2 tiene el valor tu turno
       TxtUser2.setText("Espera"); //la caja de texto 2 tiene el valor espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   }   
   //En esta parte del código estamos llevando a cabo la comparación nesesaria para ver quien gana en el juego 
   if(boton1.getIcon().toString().equals(boton2.getIcon().toString())&&(boton1.getIcon().toString().equals(boton3.getIcon().toString()))){
       JOptionPane.showMessageDialog(null, "Has ganado,si deseas volver a jugar da clic en reset");
    }else if
       (boton1.getIcon().toString().equals(boton4.getIcon().toString())&&(boton1.getIcon().toString().equals(boton7.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }else if(boton1.getIcon().toString().equals(boton5.getIcon().toString())&&(boton1.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            } 
               
    
    }//GEN-LAST:event_boton1MouseClicked

    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
        if (TxtUser1.getText().equals("Tu turno")){//la caja de texto 2 tiene el valor tu turno
       boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));//asignamos la imagen que corresponde
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por su turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   }  else if (TxtUser2.getText().equals("Tu turno")){//la caja de texto 2 tiene el valor tu turno
       boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));//Se pone la imagen contraria a la x
       
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));//estamos poniendo un color
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));//estamos poniendo un color
   } 
        //En esta parte del código estamos llevando a cabo la comparación nesesaria para ver quien gana en el juego 
        if(boton1.getIcon().toString().equals(boton2.getIcon().toString())&&(boton1.getIcon().toString().equals(boton3.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
        }else if(boton2.getIcon().toString().equals(boton5.getIcon().toString())&&(boton2.getIcon().toString().equals(boton8.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
       
        
        
    }//GEN-LAST:event_boton2MouseClicked

    private void boton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton3MouseClicked
         if (TxtUser1.getText().equals("Tu turno")){//la caja de texto 2 tiene el valor tu turno
       boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));//agregamos lo que es el icono a lo que es el boton
      
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   }  else if (TxtUser2.getText().equals("Tu turno")){//estamos evaluando si enrealidad dice tu turno
       boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));
       
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   }   
         //En esta parte del código estamos llevando a cabo la comparación nesesaria para ver quien gana en el juego 
         if(boton1.getIcon().toString().equals(boton2.getIcon().toString())&&(boton1.getIcon().toString().equals(boton3.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if(boton3.getIcon().toString().equals(boton6.getIcon().toString())&&(boton3.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }else if(boton3.getIcon().toString().equals(boton5.getIcon().toString())&&(boton3.getIcon().toString().equals(boton7.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
         
    }//GEN-LAST:event_boton3MouseClicked

    private void boton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton4MouseClicked
         if (TxtUser1.getText().equals("Tu turno")){
       boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));
       
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   }  else if (TxtUser2.getText().equals("Tu turno")){//evaluamos que diga tu turno
       boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));//cambiamos que lo cambie a o
       
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
TxtUser1.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   } 
         //En esta parte del código estamos llevando a cabo la comparación nesesaria para ver quien gana en el juego 
         if (boton4.getIcon().toString().equals(boton5.getIcon().toString())&&(boton4.getIcon().toString().equals(boton6.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if
       (boton1.getIcon().toString().equals(boton4.getIcon().toString())&&(boton1.getIcon().toString().equals(boton7.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
    }//GEN-LAST:event_boton4MouseClicked

    private void boton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton5MouseClicked
           if (TxtUser1.getText().equals("Tu turno")){//verificamos que en realidaddiga tu turno
       boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));
       
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   }  else if (TxtUser2.getText().equals("Tu turno")){//verifica que en realidad se igual a  tu turno
       boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));//cmabia la imagen de x a o
       
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));//asignamos el color a la caja
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));//asignamos el color a la caja
   } 
           
           //aqui estamos haciendo la comparacion donde quien gano
            if (boton4.getIcon().toString().equals(boton5.getIcon().toString())&&(boton4.getIcon().toString().equals(boton6.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if(boton2.getIcon().toString().equals(boton5.getIcon().toString())&&(boton2.getIcon().toString().equals(boton8.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }else if(boton1.getIcon().toString().equals(boton5.getIcon().toString())&&(boton1.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }else if(boton3.getIcon().toString().equals(boton5.getIcon().toString())&&(boton3.getIcon().toString().equals(boton7.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
    }//GEN-LAST:event_boton5MouseClicked

    private void boton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton6MouseClicked
       if (TxtUser1.getText().equals("Tu turno")){//verificamos que en realidad diga tu turno
       boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));
       
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));
   }  else if (TxtUser2.getText().equals("Tu turno")){//verificamos que diga tu turno
       boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));
      
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));// estamos poniendo un color
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));// estamos poniendo color
   } 
       if (boton4.getIcon().toString().equals(boton5.getIcon().toString())&&(boton4.getIcon().toString().equals(boton6.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if(boton3.getIcon().toString().equals(boton6.getIcon().toString())&&(boton3.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
    }//GEN-LAST:event_boton6MouseClicked

    private void boton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton7MouseClicked
          if (TxtUser1.getText().equals("Tu turno")){//verificamos que diga tu turno
       boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));
      
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//estamos pornienod un color
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//estmos poniendo un color 
   }  else if (TxtUser2.getText().equals("Tu turno")){
       boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));
       
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));//estamos poniendo un color
TxtUser1.setBackground(new java.awt.Color(255,255, 0));//estmos poniendo un color
   }  
          
          //estmos haciendo las comparaciones para saber quein ganó
          if (boton7.getIcon().toString().equals(boton8.getIcon().toString())&&(boton7.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if
       (boton1.getIcon().toString().equals(boton4.getIcon().toString())&&(boton1.getIcon().toString().equals(boton7.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }else if(boton3.getIcon().toString().equals(boton5.getIcon().toString())&&(boton3.getIcon().toString().equals(boton7.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
    }//GEN-LAST:event_boton7MouseClicked

    private void boton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton8MouseClicked
         if (TxtUser1.getText().equals("Tu turno")){//estamos verificanod que diga tu turno
       boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));
      
       TxtUser1.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));//estamos poniendo unn color
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));//esamos piniendo un color
   }  else if (TxtUser2.getText().equals("Tu turno")){
       boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));
       
       TxtUser1.setText("Tu turno");//Cambiamos su valor por tu turno
       TxtUser2.setText("Espera");//Cambiamos su valor por espera
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));
   } 
          if (boton7.getIcon().toString().equals(boton8.getIcon().toString())&&(boton7.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if(boton2.getIcon().toString().equals(boton5.getIcon().toString())&&(boton2.getIcon().toString().equals(boton8.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
    }//GEN-LAST:event_boton8MouseClicked

    private void boton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton9MouseClicked
             if (TxtUser1.getText().equals("Tu turno")){
       boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/x.jpg")));
       
       TxtUser1.setText("Espera");
       TxtUser2.setText("Tu turno");
       TxtUser1.setBackground(new java.awt.Color(255,0, 51));
       TxtUser2.setBackground(new java.awt.Color(255,255, 0));
       
   }  else if (TxtUser2.getText().equals("Tu turno")){
       boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/o.jpg")));
       
       TxtUser1.setText("Tu turno");
       TxtUser2.setText("Espera");
       TxtUser2.setBackground(new java.awt.Color(255,0, 51));
       TxtUser1.setBackground(new java.awt.Color(255,255, 0));
   } 
              if (boton7.getIcon().toString().equals(boton8.getIcon().toString())&&(boton7.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
    }else if(boton3.getIcon().toString().equals(boton6.getIcon().toString())&&(boton3.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado");
            }else if(boton1.getIcon().toString().equals(boton5.getIcon().toString())&&(boton1.getIcon().toString().equals(boton9.getIcon().toString()))){
       JOptionPane.showMessageDialog(null,"Has ganado,si deseas volver a jugar da clic en reset");
            }
    }//GEN-LAST:event_boton9MouseClicked

    private void TxtUser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUser1ActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUser1ActionPerformed

    private void limpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limpActionPerformed
//este es el boton dentro del cual on esta diciendo que borre y regrese a la primer imagen 
    private void limpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpMouseClicked
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
        boton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tom.jpg")));
       JOptionPane.showInputDialog("Nombre del jugador 1");
       JOptionPane.showInputDialog("Nombre del jugador 2");
    }//GEN-LAST:event_limpMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoGato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoGato().setVisible(true);
            }
             
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtUser1;
    private javax.swing.JTextField TxtUser2;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton limp;
    // End of variables declaration//GEN-END:variables
}
